config/routes.rb
Rails.application.routes.draw do

  get 'pages/feed'

  get 'pages/about'

  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def feed
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.title %></td>
        <td><%= group.body %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us at Greeny Coders Group</h1>
<h2 class="subtitle">Movie Reviews at: https//:www.moviereviews.utah.com</h2>
<p>fake link btw</p>

<div class="link"><%= render "shared/links" %></div>
<h1>Jeremy Titensor, Isabella Gilman, Lane Allan, Connor Cisney</h1>
<div class="link">
  <a href="https://github.com/autoreflex24/group_project"> Github Link</a>
</div>

app/views/pages/feed.html.erb
<h1 class="title">The fastest newest feed on the Web!</h1>
<h2 class="subtitle">You shouldn't doubt our greeny version of a PERFECT system! :D</h2>

<hr>

    <div class="title"><h1>The Spongebob Movie</h1></div>
    <div class="subtitle"><h2>By Dovahkiin</h2></div>
    <p>This was a great movie, I've never seen it before. 10/10.</p>
  
    <div class="image">
      <img src="https://lh3.googleusercontent.com/-xJiPTMAglC4/VhAGkwzpB5I/AAAAAAAA9t4/pvdLJ75PXdM/w300-h317/15%2B-%2B1%2B%25289%2529.gif">
    </div>
    
    <hr>

  <div class="title"><h1>The Hunger Games</h1></div>
  <div class="subtitle"><h2>Best movie in decades</h2></div>
  <p>It was cool and stuff.</p>
  
    <div class="image">
      <img src="https://media.tenor.com/images/5221da6d1ecdf33cb717519819ff6dc9/tenor.gif">
    </div>

<div class="link"><%= render "shared/links" %></div>

app/views/pages/home.html.erb
<h1 class="title">Hello Movie Goers!</h1>
<h2 class="title">This is the BRAND NEW Moview Review page!</h2>
<p>Find me in app/views/pages/home.html.erb</p>
<div class="link"><%= render "shared/links" %></div>

app/views/shared/_links.html.erb
<div class="link">
  <%= link_to "Home", root_path %>
  <%= link_to "Feed", pages_feed_path %>
  <%= link_to "About", pages_about_path %>
</div>